"""empty message

Revision ID: f68513d14753
Revises: 
Create Date: 2019-07-12 18:36:47.695362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68513d14753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveypicture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture_filename', sa.String(length=15), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveypicture')
    # ### end Alembic commands ###
